---
# tasks file for tower_ldap_settings
- name: Configure Tower LDAP Settings
  tower_ldap_settings:
      ldap_server_name: "{{ server_name |default(omit) }}"
      ldap_bind_dn: "{{ bind_dn | default(omit) }}"
      ldap_bind_password: "{{ bind_password | default(omit) }}"
      ldap_user_search: "{{ user_search | default(omit) }}"
      ldap_group_search: "{{ group_search | default(omit) }}"
      ldap_superuser: "{{ superuser | default(omit) }}"
      ldap_organization_map: "{{ organization_map | default(omit) }}"
      ldap_team_map: "{{ team_map | default(omit)}}"
      state: "{{ ldap_state | default(present) }}"
      tower_host: "{{ host | default(omit)}}"
      tower_username: "{{ username | default(omit) }}"
      tower_password: "{{ password | default(omit)}}"
